### ISSUE TITLE
avatar color changes for same user

### ISSUE THREAD

**Issue by NaBo1985** [hrueger/nativescript-letter-avatar#43]
I am facing an issue where I am developing a chat app and each time the same user sends a message the color of his avatar changes. I would like to know if there is a way to consistently keep a specific color for each user(by assigning a unique ID to the avatar). For example when a new user is added to a chat room he will randomly be given a color and that color will only be his, his color won't change with every message he sends and no other user will have his color.

**Comment by hrueger** [comment]
This happens by design, so it is not your fault. See [those lines](https://github.com/hrueger/nativescript-letter-avatar/blob/6782fe48139abc1a07e2179aca4e80f28993c2ab/src/letter-avatar.ts#L77-L78
) for reference.
However, I totally understand that a constant color would make more sense. 

You should be able to set the background color yourself, see the third code block in the Readme. You could for example generate your own colors for every user and save them in your database (or wherever else you save the users).

Is this what you'd like to achieve?

**Comment by NaBo1985** [comment]
thank you... ill look into it
